### ISSUE TITLE
Not showing annotations for ASIA

### ISSUE THREAD

**Issue by mital87** [thoughtbot/TBAnnotationClustering#10]
Hello, 
My Annotation works perfectly for USA. but i have passed London's coordinate then annotations not display. please help me out to resolve this issue.

Thanking You in advance.

**Comment by eyaldar** [comment]
Hi @mital87,

My guess is that TBBoundingBox's intersect and contains functions works correctly only for some parts of the worlds due to too simple condition.
Geographic coordinates ranges are -90 to 90 for latitude and -180 to 180 for longitude, and as such the conditions wouldn't work correctly for anything on the opposite direction after longitude and latitude of zero.
Also, note that the world's bonding box defined in the "buildTree" function limit the tree to box of:
x0:19, y0: -166, xf:72, yf:-53.
